version: '3'

networks:
  default:
    external:
      name: main

services:
  terminal:
    build: .
    container_name: terminal
    restart: unless-stopped
    environment:
      - ENABLE_TRACKING=${ENABLE_TRACKING}
      - TRACKING_URL=${TRACKING_URL}
      - TRACKING_SITE_ID=${TRACKING_SITE_ID}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 200s
      timeout: 200s
      retries: 5
